---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen
